services:
  movies-api-node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movies-api-node
    ports:
      - "50702:8000"
    restart: unless-stopped
    # Optional healthcheck (nice for labs)
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8000/movies"]
      interval: 20s
      timeout: 5s
      retries: 5
